### ISSUE TITLE
Add route for refreshing token

### ISSUE THREAD

**Issue by codekeyz** [nahidulhasan/lumen-jwt-api#1]
Consider adding a route with refresh token implementation. It will be useful for people who come across this starter.

**Comment by osbre** [comment]
## From docs:
https://jwt-auth.readthedocs.io/en/develop/quick-start/#create-the-authcontroller

### Controller
```
    /**
     * Refresh a token.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function refresh()
    {
        return $this->respondWithToken(auth()->refresh());
    }
```
### Route 
`    Route::post('refresh', 'AuthController@refresh');
`

**Comment by codekeyz** [comment]
Great. Works fine.
